### ISSUE TITLE
can it work if I use iGPU to display?

### ISSUE THREAD

**Issue by Niculuse** [foucault/nvfancontrol#11]
If I install nvidia driver with option --no-opengl-files, and I use an integrated GPU to display leaving nvidia GPUs for deep learning, dose this fan speed control work?

**Comment by foucault** [comment]
The short answer is: no. nvfancontrol uses the same infrastructure as nvidia-settings and that requires an X server attached to the display.

The long answer is: maybe if you are willing to experiment. Since you installed the driver with `--no-opengl-files` there is a chance `xvfb` might help. First you probably need to add `Option "AllowEmptyInitialConfiguration"` to the `20-nvidia.conf` file in addition to the existing options is `Section "Device"`. Then you may be able to use [`xvfb-run`](https://linux.die.net/man/1/xvfb) to start nvfancontrol with a command similar to (you might need to adjust the server options; see the manpage).

`xvfb-run -a -s "-screen 0 640x480x24 +extension RANDR" -- ./nvfancontrol -d`

If this does not work you might want to try to "fake" a screen. There is a [detailed guide](https://sites.google.com/site/akohlmey/random-hacks/nvidia-gpu-coolness) if you are willing to try!

**Comment by Niculuse** [comment]
Thanks for your answering. If I install nvidia driver with opengl component, and then use prime-select intel to swith to iGPU for displaying. In this case, I found I couldn't nvidia-settings anymore. Do you know how to solve it? Thanks anyway。

**Comment by foucault** [comment]
In that case if the `xvfb-run` method doesn't work then probably the only other way would be to fake a screen using the guide I linked.

**Comment by foucault** [comment]
Closed due to inactivity and lack of information.
