### ISSUE TITLE
How to be without GUI?

### ISSUE THREAD

**Issue by bizlevel** [foucault/nvfancontrol#13]
```
./nvfancontrol
WARN - No config file found; using default curve
ERROR - XNVCtrl failed: XOpenDisplay failed; is $DISPLAY set?

```

**Comment by foucault** [comment]
Everything that uses the nvidia-settings API (and that includes `nvfancontrol`) requires an X11 context. This is essentially the same issue as #11 (how to run the program without having an X11 display attached to the NVIDIA GPU) so you might want to try some your luck with Xvfb instead of a proper X11 display.
